version: ci.{build}
image: Visual Studio 2015
clone_depth: 1
init:
# Setup QT 5.9 - 64Bit

- set QTDIR=C:\Qt\5.9\msvc2015_64
- set PATH=%QTDIR%\bin;%PATH%

# Setup MSVC - VS 2015

- CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

# Get the libraries

- ps: Start-FileDownload 'https://github.com/GoldenCheetah/WindowsSDK/releases/download/v0.1.1/gc-ci-libs.zip' -Filename 'c:/gc-ci-libs.zip'
- 7z x c:/gc-ci-libs.zip -oC:\libs

install:
# choco install winflexbison
- copy qwt\qwtconfig.pri.in qwt\qwtconfig.pri
- copy c:\libs\gcconfig64-Release.appveyor.pri src\gcconfig.pri

build_script:
- qmake.exe build.pro -r -spec win32-msvc
- nmake
- cd src\release
# copy dependencies
- windeployqt GoldenCheetah.exe
- copy c:\libs\10_Precompiled_DLL\usbexpress_3.5.1\USBXpress\USBXpress_API\Host\x64\SiUSBXp.dll
- copy c:\libs\10_Precompiled_DLL\libsamplerate64\lib\libsamplerate-0.dll
- copy c:\libs\10_Precompiled_DLL\VLC\win64\lib\libvlc*.dll
# minimum test
- GoldenCheetah --version
# cleanup
- del *.h *.cpp *.obj *.pdb *.res
# pack and upload to transfer.sh
- 7z a GoldenCheetah.zip *
- curl --upload-file GoldenCheetah.zip https://transfer.sh/GoldenCheetah.zip
- cd ..\..

#notifications:
#- provider: GitHubPullRequest
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: true
